spring.application.name=trabalho_xandy
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/trabalho_xandy}
spring.datasource.username=${DB_USUARIO:postgres}
spring.datasource.password=${DB_SENHA:admin}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
